### ISSUE TITLE
Selected/Filled state not using primary color text

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-select#150]
## Describe the bug

The auro-select now shows the selected item in secondary (gray) text rather than the primary (black) text that it is designed to have. This causes inconsistencies when multiple types of input components sit next to each other (auro- input, dropdown, datepicker all use primary text for filled states.

## To Reproduce

 
You can view on the auro doc site on 2.8.1.
![image](https://user-images.githubusercontent.com/34354487/216395067-b30214b9-83e0-4894-a084-d87a0ac0ce9f.png)

Our flight search test env is on 2.8.0 and has the issue too.
![image](https://user-images.githubusercontent.com/34354487/216394877-d6b12750-fe30-4cfb-827a-52e5b0f2a029.png)

## Expected behavior

Should match design specs and use -primary-on-light.

## Screenshots

See above.

**Comment by leeejune** [comment]
Original design intention:
When label=true, placeholder=true, placeholder is text-primary in _default_ state.
When label=true, placeholder=true, placeholder is text-primary in _filled_ state.


Current:
When label=true, placeholder=true, placeholder is text-secondary in _default_ state.
When label=true, placeholder=true, placeholder is text-secondary in _filled_ state.

Change requested:
When label=true, placeholder=true, placeholder is text-secondary in _default_ state.
When label=true, placeholder=true, placeholder is text-primary in _filled_ state.

Due to complexities in engineering, we will be making the placeholder text-primary only when it is in the filled state. The original design was to have the placeholder text-primary at all times.
