### ISSUE TITLE
Don't use loops to figure out which item is selected

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-select#40]
## Describe the bug

Currently this code is what is in there:

      for (let optionsIndex = 0; optionsIndex < this.items.length; optionsIndex += 1) {
        if (this.items[optionsIndex].hasAttribute('selected')) {
          focusIndex = optionsIndex;
        }
      }
      
Instead we should just do something like `focusIndex = this.items.indexOf(evt.target);`

**Comment by blackfalcon** [comment]
What issue is this code causing? What is a proposed refactor?

**Comment by blackfalcon** [comment]
Reference: https://github.com/AlaskaAirlines/auro-select/pull/35#discussion_r809531053

**Comment by blackfalcon** [comment]
The proposed `focusIndex = this.items.indexOf(evt.target);` doesn't take into account the `selected` attribute? This will just return the index of the targeted element? 

The purpose of this code is to roll through all the options in a menu and return the index of the one option with the `selected` attribute. 

Although, this will need to be updated to an array since there is a future ask to have multiple selected options. But... future.

**Comment by jason-capsule42** [comment]
This whole section of code is only being used to apply .focus(). Focus is only ever going to go onto the menuoption that was clicked on. Since that menuoption is already known from the click event where this code executes there is no need to re-find the same object that was already passed in with event.target.

That said, since we are looking at moving forward with the aria solution in the future we would not be applying focus to menuoptions in the future. So I propose we ignore this ticket and just close it out.
